# Configuration file for dnsmasq.
server=9.9.9.9
server=8.8.8.8
interface=wlan0
port=53
domain-needed
bogus-priv
strict-order
expand-hosts
domain=example.com
listen-address=127.0.0.1
dhcp-range=192.168.55.50,192.168.55.150,12h
