#!/bin/bash
SECONDS=0
echo ""
echo "perform sudo apt-get update"
sudo apt-get update||echo "failed: sudo apt-get update"
echo ""
echo "perform sudo apt-get -y install network-manager"
sudo apt-get -y install network-manager||echo "failed: sudo apt-get -y install network-manager"
echo ""
echo "perform sudo apt-get -y install wireshark"
sudo apt-get -y install wireshark||echo "failed: sudo apt-get -y install wireshark"
echo "perform sudo usermod -a -G wireshark $USER"
sudo usermod -a -G wireshark $USER
echo "perform sudo apt-get -y install tshark"
sudo apt-get -y install tshark||echo "failed: sudo apt-get -y install tshark"
echo ""
echo "perform sudo apt-get -y install net-tools"
sudo apt-get -y install net-tools||echo "failed: sudo apt-get -y install net-tools"
echo ""
echo "perform sudo apt-get -y install wireless-tools"
sudo apt-get -y install wireless-tools||echo "failed: sudo apt-get -y install wireless-tools"
echo ""
echo "perform sudo apt-get -y install iw"
sudo apt-get -y install iw||echo "failed: sudo apt-get -y install iw"
echo ""
echo "perform sudo apt-get -y install make"
sudo apt-get -y install make||echo "failed: apt-get -y install make"
echo ""
echo "perform sudo apt-get -y install dkms"
sudo apt-get -y install dkms||echo "failed: sudo apt-get -y install dkms"
echo ""
echo "perform sudo apt-get install screen"
sudo apt-get -y install screen||echo "failed: sudo apt-get install screen"
echo ""
echo "perform sudo apt-get -y install dphys-swapfile"
sudo apt-get -y install dphys-swapfile||echo "failed: sudo apt-get -y install dphys-swapfile"
echo ""
echo "perform sudo apt-get -y install dphys-swapfile"
sudo sudo apt-get -y install rfkill||echo "failed: sudo sudo apt-get -y install rfkill"
echo ""
echo "perform configuretion of swap file in /etc/dphys-swapfile"
sudo sed -i -e 's/#CONF_SWAPFILE/CONF_SWAPFILE/g' /etc/dphys-swapfile
sudo sed -i -e 's/#CONF_SWAPFACTOR/CONF_SWAPFACTOR/g' /etc/dphys-swapfile
sudo sed -i -e 's/#CONF_MAXSWAP/CONF_MAXSWAP/g' /etc/dphys-swapfile
echo ""
echo "perform sudo chmod +x /usr/bin/dumpcap"
sudo chmod +x /usr/bin/dumpcap||echo "failed: sudo apt-get update"
duration=$SECONDS
echo ""
echo "Installation needed:"
echo "$((duration / 60)) minutes and $((duration % 60)) seconds elapsed."
echo "reboot needed"
