network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlan0:
      dhcp4: true
      dhcp6: false
      optional: true
      access-points:
        "wifiap":
          auth:
            key-management: psk
            password: "password"
          mode: ap
          band: 2.4GHz
          networkmanager:
            passthrough:
              wifi-security.proto: "rsn" # WPA2 only
