# Wi-Fi Router

# interface and driver
interface=wlan0
driver=nl80211

# WiFi configuration
ssid=wifiap
channel=1
hw_mode=g
country_code=DE

# WiFi encryption
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_passphrase=password
